//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLURecruit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Info()
        {
            this.Recruitments = new HashSet<Recruitment>();
        }
    
        public int Id { get; set; }
        public string Name_Company { get; set; }
        public string Introduce_Company { get; set; }
        public string website_Company { get; set; }
        public string Logo_Comany { get; set; }
        public string Field_Company { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public string Slug_Company { get; set; }
        public Nullable<int> Is_hot_Company { get; set; }
        public int Id_Status { get; set; }
        public string Id_Account { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Status_Account Status_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recruitment> Recruitments { get; set; }
    }
}
