//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLURecruit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Info
    {
        public int Id { get; set; }
        public string Student_Name { get; set; }
        public Nullable<System.DateTime> Student_Birthday { get; set; }
        public Nullable<bool> Student_Gender { get; set; }
        public string Student_Description { get; set; }
        public string Student_PhoneNumber { get; set; }
        public string Student_Photo { get; set; }
        public Nullable<System.DateTime> Student_Create_at { get; set; }
        public Nullable<System.DateTime> Student_Update_at { get; set; }
        public Nullable<int> Student_faculty_id { get; set; }
        public int Status_Id { get; set; }
        public string Account_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Status_Account Status_Account { get; set; }
    }
}
